# Generated by Django 2.2.7 on 2020-06-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0002_auto_20200601_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='用户名', max_length=200, verbose_name='用户名'),
        ),
    ]
