# Generated by Django 2.2.7 on 2020-06-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0005_goods_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(help_text='订单id', verbose_name='订单id'),
        ),
    ]
