# Generated by Django 2.2.7 on 2020-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0006_auto_20200605_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closed_time',
            field=models.DateTimeField(blank=True, help_text='交易关闭时间', null=True, verbose_name='交易关闭时间'),
        ),
    ]
